routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::resource('page', 'HomeController')->only('edit', 'update');
Route::resource('gallery', 'GalleryController');
Route::resource('news', 'NewsController');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    {{ __('messages.welcome') }}
                    <span class="float-right">
                        <a class="text-muted" href="{{ route('page.edit', ['id' => $page->id]) }}" role="button">
                            {{ __('messages.edit') }}
                        </a>
                    </span>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ $page->body }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection