routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::resource('page', 'HomeController')->only('edit', 'update');
Route::resource('gallery', 'GalleryController');
Route::resource('news', 'NewsController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<!-- IP: {{Request::getClientIp()}} -->
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    @if (isset($meta['desc']))
<meta name="description" content="{{$meta['desc']}}">
@endif
    <title>{{ config('app.name', 'Laravel') }} - {{$meta['title']}}</title>

    <!-- Fonts -->
    <link href="//fonts.gstatic.com" rel="dns-prefetch">
    <link href="//fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="//use.fontawesome.com/releases/v5.6.3/css/all.css" rel="stylesheet" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/scrollup.css') }}" rel="stylesheet">
    @if (Request::is('gallery/*') || Request::path() === 'gallery')
<link href="{{ asset('css/album.css') }}" rel="stylesheet">
    <link href="{{ asset('css/jquery.fancybox.min.css') }}" rel="stylesheet">
@endif
</head>
<body>
    <div id="app">
        @include('layouts.nav')

        <main class="py-4">
            @yield('content')

        </main>
    </div>

    @include('layouts.footer')
</body>
</html>

resources/views/layouts/errors.blade.php
@if ($errors->any())
    <div class="row justify-content-center">
        <div class="col-md-6 mb-1">
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endif

resources/views/layouts/footer.blade.php
    <a href="#app" id="scrollup"><i class="fas fa-arrow-circle-up"></i></a>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/scrollup.js') }}" defer></script>
@if (Request::is('gallery/*') || Request::path() === 'gallery')
    <script src="{{ asset('js/jquery.fancybox.min.js') }}" defer></script>
@endif
    <!-- {{ $copyright }} -->

resources/views/layouts/nav.blade.php
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link{{ Request::is('news/*') || Request::path() === 'news' ? ' active' : '' }}" href="{{ route('news.index') }}">{{ __('messages.news') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link{{ Request::is('gallery/*') || Request::path() === 'gallery' ? ' active' : '' }}" href="{{ route('gallery.index') }}">{{ __('messages.gallery') }}</a>
                        </li>
                    </ul>
                    <span class="navbar-text">{{ $action }}</span>
                </div>
            </div>
        </nav>