routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::resource('page', 'HomeController')->only('edit', 'update');
Route::resource('gallery', 'GalleryController');
Route::resource('news', 'NewsController');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Libraries\DateFormat;

class News extends Model
{
    protected $fillable = ['title', 'body']; // Доступные для заполнения поля
    protected $perPage  = 3; // Количество новостей на странице

    /**
     * Преобразуем дату создания новости в соответствии с правилами русского языка
     *
     * @param $attr
     *
     * @return array|\Illuminate\Contracts\Translation\Translator|string|null
     */
    public function getCreatedAtAttribute($attr)
    {
        return DateFormat::post($attr);
    }

    /**
     * Преобразуем дату обновления новости в соответствии с правилами русского языка
     *
     * @param $attr
     *
     * @return array|\Illuminate\Contracts\Translation\Translator|string|null
     */
    public function getUpdatedAtAttribute($attr)
    {
        return DateFormat::post($attr);
    }
}

resources/views/pages/edit.blade.php
@extends('layouts.app')

@section('content')
    @php
        /** @var \Form */
    @endphp
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 mb-1">
                {{ Form::model($page, ['route' => ['page.update', $page->id]]) }}
                <div class="card">
                    @method('PATCH')
                    <div class="card-header">
                        <div class="form-group">
                        {{ Form::label('title', __('messages.title')) }}
                        {{ Form::text('title', $page->title, ['class' => 'form-control', 'required' => true]) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('alias', __('messages.alias')) }}
                            {{ Form::text('alias', $page->alias, ['class' => 'form-control', 'disabled' => true]) }}
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            {{ Form::label('description', __('messages.desc')) }}
                            {{ Form::text('description', $page->description, ['class' => 'form-control', 'required' => true]) }}
                        </div>
                        <div class="form-group">
                        {{ Form::label('body', __('messages.body')) }}
                        {{ Form::textarea('body', $page->body, ['class' => 'form-control', 'required' => true]) }}
                        </div>
                    </div>
                    <div class="card-footer text-muted">
                        {{ __('messages.created') }}{{ $page->created_at }}
                        @if ($page->updated_at > $page->created_at)
                            <span class="float-right">
                            {{ __('messages.updated') }}{{ $page->updated_at }}
                        </span>
                        @endif
                    </div>
                </div>
                <div class="text-center mt-2">
                    {{ Form::submit(__('messages.save'), ['class' => 'btn btn-primary']) }}
                    <a class="btn btn-secondary" href="{{ url('/') }}" role="button">{{ __('messages.cancel') }}</a>
                </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
@endsection